version: '3.9'

services:
  frontend-service:
    image: articulate-app:latest
    container_name: frontend
    build:
      context: ./app
    ports:
      - "7990:80"
    depends_on:
      - articulate-service

  categories-service:
    image: categories:latest
    container_name: categories
    build:
      context: ./categories
    ports:
      - "7991:81"

  numbers-service:
    image: numbers:latest
    container_name: numbers
    build:
      context: ./numbers
    ports:
      - "7992:82"

  articulate-service:
    image: articulate:latest
    container_name: articulate
    build:
      context: ./articulate
    ports:
      - "7993:83"
    depends_on:
      - numbers-service
      - categories-service
