version: '3.9'

services:
  frontend-service:
    image: wray27/articulate-app:latest
    container_name: frontend
    domainname: "awarticulate"
    build:
      context: ./app
    ports:
      - "${WEBPORT}:80"
    depends_on: 
      - articulate-service
    deploy:
        resources:
          limits:
            cpus: '1.00'
            memory: 1G
          reservations:
            cpus: '0.5'
            memory: 0.5GB
    
  categories-service:
    image: wray27/categories:latest
    container_name: categories
    build:
      context: ./categories
    ports:
      - "81:81"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5G
        reservations:
          cpus: '0.25'
          memory: 0.2GB
    
  numbers-service:
    image: wray27/numbers:latest
    container_name: numbers
    build:
      context: ./numbers
    ports:
      - "82:82"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5G
        reservations:
          cpus: '0.25'
          memory: 0.2GB

  articulate-service:
    image: wray27/articulate:latest
    container_name: articulate
    build:
      context: ./articulate
    ports:
      - "83:83"
    depends_on:
      - numbers-service
      - categories-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5G
        reservations:
          cpus: '0.25'
          memory: 0.2GB
    
