version: '3.9'

services:
  frontend-service:
    image: wray27/articulate-app:latest
    container_name: frontend
    domainname: "awarticulate"
    build:
      context: ./app
    ports:
      - "${WEBPORT}:80"
    depends_on: 
      - articulate-service

  categories-service:
    image: wray27/categories:latest
    container_name: categories
    build:
      context: ./categories
    ports:
      - "81:81"

  numbers-service:
    image: wray27/numbers:latest
    container_name: numbers
    build:
      context: ./numbers
    ports:
      - "82:82"

  articulate-service:
    image: wray27/articulate:latest
    container_name: articulate
    build:
      context: ./articulate
    ports:
      - "83:83"
    depends_on:
      - numbers-service
      - categories-service

